Repository lidofinance/community-staking-module, pull requests merged in 2025-08, with the labels that each got.

#553 chore: add PR template and dev guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: docs, chore

#554 Revert "fix: strike params on Hoodi (#550)"
  script/DeployHoodi.s.sol
Labels: chore

#562 chore: Fix several INFO findings by Statemind
  src/CSModule.sol
  src/lib/NOAddresses.sol
  test/CSModule.t.sol
Labels: audit, v2, chore

#564 Sync `main` with `develop`
  .foundryref
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/regular-mainnet.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Justfile
  README.md
  artifacts/hoodi/ics/README.md
  artifacts/hoodi/ics/addresses.json
  artifacts/hoodi/ics/ics.csv
  artifacts/hoodi/ics/main.py
  artifacts/hoodi/ics/merkle-proofs.json
  artifacts/hoodi/ics/merkle-tree.json
  artifacts/hoodi/ics/sources/extra_addresses.json
  artifacts/hoodi/transactions-v2-upgrade.json
  artifacts/hoodi/upgrade-v2-hoodi.json
  artifacts/mainnet/deploy-mainnet.json
  artifacts/mainnet/ics/addresses.json
  artifacts/mainnet/ics/exclude/pros.json
  artifacts/mainnet/ics/exclude/self_exclusion.json
  artifacts/mainnet/ics/ics.csv
  artifacts/mainnet/ics/main.py
  artifacts/mainnet/ics/merkle-proofs.json
  artifacts/mainnet/ics/merkle-tree.json
  fork.just
  script/DeployHoodi.s.sol
  script/DeployMainnet.s.sol
  src/CSModule.sol
  src/interfaces/ICSModule.sol
  src/lib/NOAddresses.sol
  test/CSModule.t.sol
  test/fork/integration/CreateAndDeposit.sol
  test/fork/integration/Ejection.t.sol
  test/fork/integration/StakingRouter.t.sol
  test/helpers/Fixtures.sol
Labels: audit, CSM v2

#574 chore: Improve func docs
  src/CSModule.sol
  src/interfaces/ICSModule.sol
Labels: CSM v2, chore

#571 CSM tests for Curated v2
  src/CuratedModule.sol
  test/CSModule.t.sol
  test/CuratedModule.t.sol
  test/ModuleAbstract.t.sol
  test/fork/integration/ClaimInTokens.t.sol
  test/fork/integration/CreateAndDeposit.sol
  test/fork/integration/Oracle.t.sol
  test/fork/integration/Penalty.t.sol
  test/fork/integration/RecoverTokens.t.sol
  test/fork/integration/StakingRouter.t.sol
  test/fork/integration/misc/Invariants.t.sol
  test/helpers/InvariantAsserts.sol
Labels: tests, CM v2

#578 chore: Audit fixes for Statemind findings
  src/CSAccounting.sol
  src/abstract/CSBondLock.sol
  test/CSAccounting.t.sol
Labels: audit, CSM v2, chore

#577 chore: adjust calculation of historical block root gI
  src/CSVerifier.sol
  src/interfaces/ICSVerifier.sol
  test/CSVerifier.t.sol
Labels: CSM v2, refactor

#579 chore: Add minor natspec notes
  src/interfaces/ICSAccounting.sol
Labels: CSM v2, chore

#572 feat: `BondReserve.sol`
  .github/workflows/test.yml
  script/DeployBase.s.sol
  script/DeployHolesky.s.sol
  script/DeployHoodi.s.sol
  script/DeployImplementationsBase.s.sol
  script/DeployLocalDevNet.s.sol
  script/DeployMainnet.s.sol
  script/fork-helpers/SimulateVote.s.sol
  src/CSAccounting.sol
  src/abstract/BondReserve.sol
  src/interfaces/IBondReserve.sol
  src/interfaces/ICSAccounting.sol
  test/BondReserve.t.sol
  test/CSAccounting.t.sol
  test/fork/deployment/PostDeployment.t.sol
  test/fork/integration/CreateAndDeposit.sol
  test/fork/integration/misc/ProxyUpgrades.sol
  test/helpers/InvariantAsserts.sol
Labels: feature, CM v2
