Repository lidofinance/community-staking-module, pull requests merged in 2025-09, with the labels that each got.

#581 feat: Built-in reward splits
  src/CSAccounting.sol
  src/interfaces/ICSAccounting.sol
  src/lib/FeeSplits.sol
  test/CSAccounting.t.sol
Labels: feature, CSM v3, CM v2

#584 chore: Update README logo
  README.md
  logo.png
Labels: CSM v2, chore

#585 Ics updates
  artifacts/mainnet/ics/assessment/experience/eligible_node_operators_hoodi.json
  artifacts/mainnet/ics/assessment/humanity/main.py
  ics-assessment/README.md
  ics-assessment/__init__.py
  ics-assessment/engagement/_fetch_aragon_votes.py
  ics-assessment/engagement/aragon_voters.csv
  ics-assessment/engagement/gitpoap_events.csv
  ics-assessment/engagement/main.py
  ics-assessment/engagement/protocol_guild.csv
  ics-assessment/experience/_collect_hoodi_eligible.py
  ics-assessment/experience/_get_no_owners.py
  ics-assessment/experience/_get_obol_techne_holders.py
  ics-assessment/experience/_get_ssv_operators.py
  ics-assessment/experience/eligible_node_operators_hoodi.json
  ics-assessment/experience/eth-staker-solo-stakers.csv
  ics-assessment/experience/main.py
  ics-assessment/experience/node_operator_owners_hoodi.json
  ics-assessment/experience/node_operator_owners_mainnet.json
  ics-assessment/experience/obol-techne-credentials-base.csv
  ics-assessment/experience/obol-techne-credentials-bronze.csv
  ics-assessment/experience/obol-techne-credentials-silver.csv
  ics-assessment/experience/sdvtm-mainnet.csv
  ics-assessment/experience/sdvtm-testnet.csv
  ics-assessment/experience/ssv-verified-operators.csv
  ics-assessment/experience/stake-cat-gnosischain.csv
  ics-assessment/experience/stake-cat-solo-B.csv
  ics-assessment/humanity/_collect_circles.py
  ics-assessment/humanity/circle_group_members.csv
  ics-assessment/humanity/main.py
  ics-assessment/img.png
  ics-assessment/main.py
  ics-assessment/requirements.txt
  ics-assessment/tests/__init__.py
  ics-assessment/tests/test_engagement_main.py
  ics-assessment/tests/test_evaluate_window_cases.py
  ics-assessment/tests/test_experience_main.py
  ics-assessment/tests/test_humanity_main.py
Labels: chore

#586 fix: high signal score calculation
  ics-assessment/engagement/main.py
Labels: bug

#589 audit: Statemind fixes 2
  src/CSModule.sol
  src/CSStrikes.sol
  test/CSModule.t.sol
Labels: audit, CSM v2

#596 chore: update implementation addresses for hoodi
  artifacts/hoodi/upgrade-v2-hoodi.json
  script/DeployHolesky.s.sol
  script/DeployHoodi.s.sol
  test/helpers/Fixtures.sol
Labels: CSM v2

#599 chore: CSM v2 upgrade artifacts on mainnet
  artifacts/mainnet/transactions-v2-upgrade.json
  artifacts/mainnet/upgrade-v2-mainnet.json
Labels: CSM v2, chore

#594 feat: consolidations and penalty multiplier
  .gitignore
  .prettierignore
  Justfile
  fork.just
  foundry.toml
  package.json
  script/DeployBase.s.sol
  script/DeployCSVerifierElectra.s.sol
  script/DeployHolesky.s.sol
  script/DeployHoodi.s.sol
  script/DeployImplementationsBase.s.sol
  script/DeployMainnet.s.sol
  script/constants/GIndices.sol
  script/fork-helpers/NodeOperators.s.sol
  script/fork-helpers/SimulateVote.s.sol
  script/gindex.mjs
  script/ssz_list_uint64.mjs
  src/CSModule.sol
  src/CSVerifier.sol
  src/interfaces/ICSModule.sol
  src/interfaces/ICSVerifier.sol
  src/lib/SSZ.sol
  src/lib/Types.sol
  test/fixtures/CSVerifier/consolidations.mjs
  test/unit/CSVerifier.t.sol
  test/unit/CSVerifierHistorical.t.sol
  test/unit/CSVerifierHistoricalCrossForks.t.sol
  test/unit/ModuleAbstract.t.sol
  test/unit/lib/SSZ.t.sol
  yarn.lock
Labels: feature, CSM v3, CM v2
